In [19]:
# 구글 드라이브 연결 
from google.colab import drive
drive.mount('/content/drive')
folder_dir = "/content/drive/MyDrive/Colab Notebooks/"
DATA_FILE = "diabetes.csv"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [20]:
# 마운트 및 csv파일 출력

import pandas as pd
import os

# 디렉토리 경로와 파일명을 결합하여 파일 시스템 내 절대 경로를 확정
file_path = os.path.join(folder_dir, DATA_FILE)

# CSV 데이터 파싱 및 메모리 내 DataFrame 객체 생성
try:
    df = pd.read_csv(file_path)
    
    # Colab 인터랙티브 환경의 데이터 렌더링 기능을 활용한 출력
    display(df)
except FileNotFoundError:
    print(f"오류: 지정된 경로에서 파일을 식별할 수 없습니다. ({file_path})")

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [21]:
# 테스트셋, 학습셋 형성
X = df.drop('Outcome',axis = 1)
display(X)

Y=df['Outcome']
display(Y)

## 테스트 집단 추출

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y,test_size=0.25,random_state=0)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [22]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

import warnings
warnings.filterwarnings('ignore')

In [23]:
diabeteLogisticRegression = LogisticRegression(random_state=0)
diabeteLogisticRegression.fit(X_train, Y_train)

predLogisticRegression = diabeteLogisticRegression.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(Y_test, predLogisticRegression))
print (confusion_matrix(Y_test, predLogisticRegression))

--- Logistic Regression Classifier ---
0.796875
[[116  14]
 [ 25  37]]

In [ ]:
diabeteMLPClassifier = MLPClassifier(random_state=0)
diabeteMLPClassifier.fit(X_train, Y_train)

predMLPClassifier = diabeteMLPClassifier.predict(X_test)

print ("\n--- Neural Network Classifier ---")
print (accuracy_score(Y_test, predMLPClassifier))
print (confusion_matrix(Y_test, predMLPClassifier))

--- Neural Network Classifier ---
0.7239583333333334
[[103  27]
 [ 26  36]]

In [25]:
print ("\n--- Radom Forest ---")
diabeteRandomForestClassifier = RandomForestClassifier(random_state=0)
diabeteRandomForestClassifier.fit(X_train, Y_train)
predRandomForestClassifier = diabeteRandomForestClassifier.predict(X_test)
print(accuracy_score(Y_test,predRandomForestClassifier))
print (confusion_matrix(Y_test, predRandomForestClassifier))

--- Radom Forest ---
0.7708333333333334
[[116  14]
 [ 30  32]]

In [26]:
diabeteSVC = SVC(random_state=0)
diabeteSVC.fit(X_train, Y_train)

predSVC = diabeteSVC.predict(X_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(Y_test, predSVC))
print(confusion_matrix(Y_test, predSVC))

--- SVM Classifier ---
0.7708333333333334
[[119  11]
 [ 33  29]]

In [27]:

# Build a decision tree classifier and predict

diabeteDecisionTreeClassifier = DecisionTreeClassifier(random_state=0)
diabeteDecisionTreeClassifier.fit(X_train, Y_train)

predDecisionTreeClassifier = diabeteDecisionTreeClassifier.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(Y_test, predDecisionTreeClassifier))
print (confusion_matrix(Y_test, predDecisionTreeClassifier))

--- Decision Tree Classifier ---
0.71875
[[102  28]
 [ 26  36]]