In [1]:
# 구글 드라이브 연결 
from google.colab import drive
drive.mount('/content/drive')
folder_dir = "/content/drive/MyDrive/Colab Notebooks/"
DATA_FILE = "diabetes.csv"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
# 마운트 및 csv파일 출력

import pandas as pd
import os

# 디렉토리 경로와 파일명을 결합하여 파일 시스템 내 절대 경로를 확정
file_path = os.path.join(folder_dir, DATA_FILE)

# CSV 데이터 파싱 및 메모리 내 DataFrame 객체 생성
try:
    df = pd.read_csv(file_path)
    
    # Colab 인터랙티브 환경의 데이터 렌더링 기능을 활용한 출력
    display(df)
except FileNotFoundError:
    print(f"오류: 지정된 경로에서 파일을 식별할 수 없습니다. ({file_path})")

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [3]:
# 테스트셋, 학습셋 형성
X = df.drop('Outcome',axis = 1)
X = X.drop('BMI',axis = 1)
display(X)

Y=df['BMI']
display(Y)

## 테스트 집단 추출

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y,test_size=0.25,random_state=0)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,0.627,50
1,1,85,66,29,0,0.351,31
2,8,183,64,0,0,0.672,32
3,1,89,66,23,94,0.167,21
4,0,137,40,35,168,2.288,33
...,...,...,...,...,...,...,...
763,10,101,76,48,180,0.171,63
764,2,122,70,27,0,0.340,27
765,5,121,72,23,112,0.245,30
766,1,126,60,0,0,0.349,47
767,1,93,70,31,0,0.315,23

0      33.6
1      26.6
2      23.3
3      28.1
4      43.1
       ...
763    32.9
764    36.8
765    26.2
766    30.1
767    30.4
Name: BMI, Length: 768, dtype: float64

In [4]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

import pandas as pd
import numpy as np

In [5]:
diabeteLinearRegression = LinearRegression()
diabeteLinearRegression.fit(X_train, Y_train)
predLinearRegression = diabeteLinearRegression.predict(X_test)

print('평균제곱근오차', mean_squared_error(predLinearRegression, Y_test))

평균제곱근오차 52.23558099742443

In [6]:
diabeteDecisionTreeRegressor = DecisionTreeRegressor()
diabeteDecisionTreeRegressor.fit(X_train, Y_train)
predDecisionTreeRegressor = diabeteDecisionTreeRegressor.predict(X_test)

print('평균제곱근오차', mean_squared_error(predDecisionTreeRegressor, Y_test))

평균제곱근오차 76.22812499999999

In [9]:
diabeteRandomForestRegressor = RandomForestRegressor()
diabeteRandomForestRegressor.fit(X_train, Y_train)
predRandomForestRegressor = diabeteRandomForestRegressor.predict(X_test)

print('평균제곱근오차', mean_squared_error(predRandomForestRegressor, Y_test))

평균제곱근오차 46.0992291510417

In [10]:
diabeteSVR = SVR()
diabeteSVR.fit(X_train, Y_train)
predSVR = diabeteSVR.predict(X_test)

print('평균제곱근오차', mean_squared_error(predSVR, Y_test))

평균제곱근오차 49.81525695797071